### ISSUE TITLE
Add support for cuda 11.x

### ISSUE THREAD

**Issue by daw3rd** [Enterprise-Neurosystem/ai-signal-processing#3]
Cuda 10.2 is becoming more difficult to install now that some of the cuda downloads seems to have gone away.  Probably should move to a  more recent version anyway.  This will also require upgrading DL4J.

**Comment by daw3rd** [comment]
Create new branch cuda11.0 to update the pom.xml.  If you edit aisp-core-main/pom.xml to remove MainTestSuite setting, you can then run 

`mvn  -Dtest=org.eng.aisp.classifier.dcase.DCASEClassifierTest -P cuda11.0 test`

which gives the following because cuda11.0 has not been installed.

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.eng.aisp.classifier.dcase.DCASEClassifierTest
Loading aisp properties from file:/home/dawood/git/ai-signal-processing/aisp-core/aisp-core-main/aisp.properties
Aug 10, 2022 5:58:08 PM org.eng.aisp.classifier.AbstractFixableClassifier.shuffleData(AbstractFixableClassifier.java:102)
WARNING: The use of an Iterable other than IShuffleIterable has higher memory requirements.
Aug 10, 2022 5:58:08 PM org.eng.aisp.AISPRuntime.getCachingFeatureGramIterable(AISPRuntime.java:114)
INFO: Memory and/or disk caching of labeled feature/spectograms has been requested, but is ignored because caching has been disabled with the AISP/System property labeled.feature.gram.caching.enabled.  To stop this message, set this property to true to enable caching,  or change your feature gram extraction to not request caching.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Warning: Versions of org.bytedeco:javacpp:1.5.5 and org.bytedeco:cuda:11.0-8.0-1.5.4 do not match.
java.lang.UnsatisfiedLinkError: /home/dawood/.javacpp/cache/cuda-11.0-8.0-1.5.4-linux-x86_64.jar/org/bytedeco/cuda/linux-x86_64/libjnicudart.so: libcudart.so.11.0: cannot open shared object file: No such file or directory
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2445)
```

**Comment by daw3rd** [comment]
Over to @inouetster2  to work on the setup-aisp-gpu script to install the correct libraries.
